
development:
  adapter: mysql2
  database: feedstore_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: feedstore_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: feedstore_production
  username: root
  password: 
  encoding: utf8
